name: Vulnerability issue
description: Create a security issue from dependabot alerts
title: "[security]: "
labels: ["T_security"]
projects: ["PowerfulMedical/53"]
body:
  - type: markdown
    attributes:
      value: |
          You should read [Vulnerability management guide](https://infrabook.pomd.org/Security/vulnerabilities.html) before creating this issue.
  - type: input
    id: dependabot-alert
    attributes:
      label: Dependabot alert
      description: Link to the dependabot alert
  - type: dropdown
    id: likelihood-level
    attributes:
      label: Likelihood
      options:
        - Very unlikely
        - Unlikely
        - Somewhat likely
        - Likely
        - Very likely
  - type: textarea
    id: likelihood-comment
    attributes:
      label: Comment for the likelihood level
  - type: dropdown
    id: impact-level
    attributes:
      label: Impact
      options:
        - Very low
        - Low
        - Medium
        - High
        - Very high
  - type: textarea
    id: impact-comment
    attributes:
      label: Comment for the impact level
  - type: dropdown
    id: risk-score
    attributes:
      label: Risk score
      description: Calculated risk score based on likelihood and impact
      options:
        - Not relevant
        - Low
        - Medium
        - High
        - Critical
  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Any additional information that might be relevant
